# Generated by Django 5.0.6 on 2024-11-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_manage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audiorecord",
            fields=[
                (
                    "recordid",
                    models.AutoField(
                        db_column="RecordID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "counselingaudio",
                    models.TextField(
                        blank=True, db_column="CounselingAudio", null=True
                    ),
                ),
                (
                    "postopcareaudio",
                    models.TextField(
                        blank=True, db_column="PostOpCareAudio", null=True
                    ),
                ),
                (
                    "conditionchangeaudio",
                    models.TextField(
                        blank=True, db_column="ConditionChangeAudio", null=True
                    ),
                ),
            ],
            options={
                "db_table": "audiorecord",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "departmentid",
                    models.AutoField(
                        db_column="DepartmentID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "departmentname",
                    models.CharField(db_column="DepartmentName", max_length=255),
                ),
            ],
            options={
                "db_table": "department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Devicedata",
            fields=[
                (
                    "dataid",
                    models.AutoField(
                        db_column="DataID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "devicetype",
                    models.CharField(
                        blank=True, db_column="DeviceType", max_length=100, null=True
                    ),
                ),
                (
                    "datacontent",
                    models.TextField(blank=True, db_column="DataContent", null=True),
                ),
                (
                    "recorddate",
                    models.DateField(blank=True, db_column="RecordDate", null=True),
                ),
            ],
            options={
                "db_table": "devicedata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "doctorid",
                    models.AutoField(
                        db_column="DoctorID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
                (
                    "specialty",
                    models.CharField(
                        blank=True, db_column="Specialty", max_length=100, null=True
                    ),
                ),
                (
                    "contactinfo",
                    models.CharField(
                        blank=True, db_column="ContactInfo", max_length=255, null=True
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, db_column="Department", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "doctor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "documentid",
                    models.AutoField(
                        db_column="DocumentID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "admissionrecord",
                    models.TextField(
                        blank=True, db_column="AdmissionRecord", null=True
                    ),
                ),
                (
                    "dischargesummary",
                    models.TextField(
                        blank=True, db_column="DischargeSummary", null=True
                    ),
                ),
                (
                    "treatmentplan",
                    models.TextField(blank=True, db_column="TreatmentPlan", null=True),
                ),
            ],
            options={
                "db_table": "document",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Genomicdata",
            fields=[
                (
                    "geneid",
                    models.AutoField(
                        db_column="GeneID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "genesequence",
                    models.TextField(blank=True, db_column="GeneSequence", null=True),
                ),
                (
                    "analysisresult",
                    models.TextField(blank=True, db_column="AnalysisResult", null=True),
                ),
            ],
            options={
                "db_table": "genomicdata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "hospitalid",
                    models.AutoField(
                        db_column="HospitalID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "hospitalname",
                    models.CharField(db_column="HospitalName", max_length=255),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="Address", max_length=255, null=True
                    ),
                ),
                (
                    "contactinfo",
                    models.CharField(
                        blank=True, db_column="ContactInfo", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "hospital",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medicalimage",
            fields=[
                (
                    "imageid",
                    models.AutoField(
                        db_column="ImageID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "imagetype",
                    models.CharField(
                        blank=True, db_column="ImageType", max_length=50, null=True
                    ),
                ),
                (
                    "storagepath",
                    models.CharField(
                        blank=True, db_column="StoragePath", max_length=255, null=True
                    ),
                ),
                (
                    "uploaddate",
                    models.DateField(blank=True, db_column="UploadDate", null=True),
                ),
                (
                    "ctimage",
                    models.TextField(blank=True, db_column="CTImage", null=True),
                ),
                (
                    "mriimage",
                    models.TextField(blank=True, db_column="MRIImage", null=True),
                ),
                (
                    "ultrasoundimage",
                    models.TextField(
                        blank=True, db_column="UltrasoundImage", null=True
                    ),
                ),
            ],
            options={
                "db_table": "medicalimage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medicalrecord",
            fields=[
                (
                    "recordid",
                    models.AutoField(
                        db_column="RecordID", primary_key=True, serialize=False
                    ),
                ),
                ("diagnosisdate", models.DateField(db_column="DiagnosisDate")),
                (
                    "diagnosisresult",
                    models.TextField(
                        blank=True, db_column="DiagnosisResult", null=True
                    ),
                ),
                (
                    "prescription",
                    models.TextField(blank=True, db_column="Prescription", null=True),
                ),
            ],
            options={
                "db_table": "medicalrecord",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patientid",
                    models.AutoField(
                        db_column="PatientID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
                ("gender", models.CharField(db_column="Gender", max_length=6)),
                ("dateofbirth", models.DateField(db_column="DateOfBirth")),
                (
                    "contactinfo",
                    models.CharField(
                        blank=True, db_column="ContactInfo", max_length=255, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="Address", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "patient",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Standardvideo",
            fields=[
                (
                    "videoid",
                    models.AutoField(
                        db_column="VideoID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "surgicalprocedurevideo",
                    models.TextField(
                        blank=True, db_column="SurgicalProcedureVideo", null=True
                    ),
                ),
                (
                    "nursingstandardvideo",
                    models.TextField(
                        blank=True, db_column="NursingStandardVideo", null=True
                    ),
                ),
                (
                    "emergencyprocedurevideo",
                    models.TextField(
                        blank=True, db_column="EmergencyProcedureVideo", null=True
                    ),
                ),
            ],
            options={
                "db_table": "standardvideo",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Customers",
        ),
        migrations.DeleteModel(
            name="Customers2",
        ),
        migrations.DeleteModel(
            name="DataManageDataManage",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
    ]
