# Generated by Django 5.0.6 on 2024-11-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_manage",
            "0002_audiorecord_department_devicedata_doctor_document_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "dataid",
                    models.AutoField(
                        db_column="DataID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "imagetype",
                    models.CharField(
                        blank=True, db_column="ImageType", max_length=50, null=True
                    ),
                ),
                (
                    "imagepath",
                    models.CharField(
                        blank=True, db_column="ImagePath", max_length=255, null=True
                    ),
                ),
                (
                    "temperatureimage",
                    models.BinaryField(
                        blank=True, db_column="TemperatureImage", null=True
                    ),
                ),
                (
                    "recorddate",
                    models.DateField(blank=True, db_column="RecordDate", null=True),
                ),
            ],
            options={
                "db_table": "temperature",
                "managed": False,
            },
        ),
    ]
